# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "github-actions-test" ]
  pull_request:
    branches: [ "github-actions-test" ]

jobs:
  build:

    runs-on: ubuntu-latest
      # matrix:
      #   os : [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./WeatherApi/
    - name: Build
      run: dotnet build --no-restore ./WeatherApi/
      # TODO add sonarqube
    - name: Test
      run: dotnet test  --configuration Release ./WeatherApi.Tests

  image:
    needs: build  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: sandshield/heaven:wapi-latest

  deploy:
    needs: image
    runs-on: ubuntu-latest

    steps:
    - name: Authenticate with Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_USERNAME }}" | docker login -u "${{ secrets.DOCKER_HUB_PASSWORD }}" --password-stdin
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
            docker pull sandshield/heaven:wapi-latest
            docker stop wapi-dc || true
            docker rm wapi-dc   || true
            docker run -d --name wapi-dc -p 8080:8080 sandshield/heaven:wapi-latest
 
